# version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    container_name: backend
    volumes:
      - ./backend:/var/www/backend
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: frontend
    volumes:
      - ./frontend:/var/www/frontend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
  mysql:
    platform: linux/amd64
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: your_secure_password
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      #PMA_USER: root
      #PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 0 # Disable arbitrary server input
      PMA_LANGUAGE: en # Force English language
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
