FROM node:22

# Set working directory
WORKDIR /var/www/frontend

# Copy package files first (optimization for caching)
COPY ./frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY ./frontend /var/www/frontend

# Build the Next.js app
RUN npm run build

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "run", "start"]